# Based on https://docs.pypi.org/trusted-publishers/using-a-publisher/

name: release_testpypi

on: workflow_call

jobs:
    build:
        - runs-on: ubuntu-latest

        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
              python-version: 3.11
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install build
        - name: Build package
          run: python -m build


    publish-to-testpypi:
        name: upload release to TestPyPI
        needs:
            - build
        runs-on: ubuntu-latest
        environment: release_testpypi
        permissions:
            id-token: write  # IMPORTANT: mandatory for trusted publishing
        steps:
            - name: Publish distribution to TestPyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/
